//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        public Cinema()
        {
            this.CinemaSources = new HashSet<CinemaSource>();
            this.Sources = new HashSet<Source>();
            this.ShowtimeSnapshots = new HashSet<ShowtimeSnapshot>();
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CityId { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool MasterListBased { get; set; }
        public string OriginalCity { get; set; }
        public Nullable<int> CinemaNetworkId { get; set; }
        public bool Enabled { get; set; }
    
        public virtual CinemaNetwork CinemaNetwork { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<CinemaSource> CinemaSources { get; set; }
        public virtual ICollection<Source> Sources { get; set; }
        public virtual ICollection<ShowtimeSnapshot> ShowtimeSnapshots { get; set; }
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
