//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CinemaSource
    {
        public int CinemaId { get; set; }
        public int TargetSiteId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Parameter { get; set; }
    
        public virtual TargetSite TargetSite { get; set; }
        public virtual Cinema Cinema { get; set; }
    }
}
