//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.CitySources = new HashSet<CitySource>();
            this.Satellites = new HashSet<City>();
            this.Sources = new HashSet<Source>();
            this.Cinemas = new HashSet<Cinema>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> FederalDistrictId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<CitySource> CitySources { get; set; }
        public virtual ICollection<City> Satellites { get; set; }
        public virtual City SatelliteTo { get; set; }
        public virtual ICollection<Source> Sources { get; set; }
        public virtual FederalDistrict FederalDistrict { get; set; }
        public virtual ICollection<Cinema> Cinemas { get; set; }
    }
}
