//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitySource
    {
        public int CityId { get; set; }
        public int TargetSiteId { get; set; }
        public string Parameter { get; set; }
        public string URL { get; set; }
    
        public virtual TargetSite TargetSite { get; set; }
        public virtual City City { get; set; }
    }
}
