//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor
    {
        public Distributor()
        {
            this.Movies = new HashSet<Movie>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Info { get; set; }
        public string Url { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int Version { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<Movie> Movies { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
