//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MovieScheduleStatsEntities : DbContext
    {
        public MovieScheduleStatsEntities()
            : base("name=MovieScheduleStatsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CinemaSource> CinemaSources { get; set; }
        public DbSet<CitySource> CitySources { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Distributor> Distributors { get; set; }
        public DbSet<Source> Sources { get; set; }
        public DbSet<TargetSite> TargetSites { get; set; }
        public DbSet<Movie> Movies { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<ParseRun> ParseRuns { get; set; }
        public DbSet<ParseRunInfo> ParseRunInfoes { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<FederalDistrict> FederalDistricts { get; set; }
        public DbSet<CinemaNetwork> CinemaNetworks { get; set; }
        public DbSet<Cinema> Cinemas { get; set; }
        public DbSet<MovieSource> MovieSources { get; set; }
        public DbSet<ShowtimeSnapshot> ShowtimeSnapshots { get; set; }
        public DbSet<Showtime> Showtimes { get; set; }
        public DbSet<Session> Sessions { get; set; }
    
        public virtual int spCleanShowtimes(Nullable<System.DateTime> todayLeft, Nullable<System.DateTime> todayRight, Nullable<System.DateTime> today)
        {
            var todayLeftParameter = todayLeft.HasValue ?
                new ObjectParameter("todayLeft", todayLeft) :
                new ObjectParameter("todayLeft", typeof(System.DateTime));
    
            var todayRightParameter = todayRight.HasValue ?
                new ObjectParameter("todayRight", todayRight) :
                new ObjectParameter("todayRight", typeof(System.DateTime));
    
            var todayParameter = today.HasValue ?
                new ObjectParameter("today", today) :
                new ObjectParameter("today", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCleanShowtimes", todayLeftParameter, todayRightParameter, todayParameter);
        }
    
        public virtual int CleanShowtimes(Nullable<System.DateTime> todayLeft, Nullable<System.DateTime> todayRight, Nullable<System.DateTime> today)
        {
            var todayLeftParameter = todayLeft.HasValue ?
                new ObjectParameter("todayLeft", todayLeft) :
                new ObjectParameter("todayLeft", typeof(System.DateTime));
    
            var todayRightParameter = todayRight.HasValue ?
                new ObjectParameter("todayRight", todayRight) :
                new ObjectParameter("todayRight", typeof(System.DateTime));
    
            var todayParameter = today.HasValue ?
                new ObjectParameter("today", today) :
                new ObjectParameter("today", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CleanShowtimes", todayLeftParameter, todayRightParameter, todayParameter);
        }
    }
}
