//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Sources = new HashSet<Source>();
            this.Distributors = new HashSet<Distributor>();
            this.MovieSources = new HashSet<MovieSource>();
            this.ShowtimeSnapshots = new HashSet<ShowtimeSnapshot>();
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string OriginalTitle { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Archived { get; set; }
        public string Format { get; set; }
        public Nullable<System.DateTime> PreviewDate { get; set; }
        public string URL { get; set; }
        public bool Suspended { get; set; }
        public Nullable<System.DateTime> ReleaseDateGlobal { get; set; }
    
        public virtual ICollection<Source> Sources { get; set; }
        public virtual ICollection<Distributor> Distributors { get; set; }
        public virtual ICollection<MovieSource> MovieSources { get; set; }
        public virtual ICollection<ShowtimeSnapshot> ShowtimeSnapshots { get; set; }
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
