//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParseRunInfo
    {
        public int Id { get; set; }
        public int ParseRunId { get; set; }
        public int TargetSiteId { get; set; }
        public int ShowtimesCountNew { get; set; }
        public int ShowtimesCountUpdated { get; set; }
    
        public virtual ParseRun ParseRun { get; set; }
        public virtual TargetSite TargetSite { get; set; }
    }
}
