//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public Session()
        {
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int Id { get; set; }
        public string Time { get; set; }
        public int Hour { get; set; }
        public int Minute { get; set; }
        public Nullable<int> OrderIndex { get; set; }
    
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
