//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showtime
    {
        public Showtime()
        {
            this.Sessions = new HashSet<Session>();
        }
    
        public int Id { get; set; }
        public string SessionsRaw { get; set; }
        public int CinemaId { get; set; }
        public string Additional { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int MovieId { get; set; }
        public int SessionsCount { get; set; }
        public string URL { get; set; }
        public string SessionsFormat { get; set; }
        public int TargetSiteId { get; set; }
        public bool PartialyAdded { get; set; }
        public int ParseRunId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual ParseRun ParseRun { get; set; }
        public virtual TargetSite TargetSite { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
