//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowtimeSnapshot
    {
        public int CinemaId { get; set; }
        public int MovieId { get; set; }
        public System.DateTime Date { get; set; }
        public int TargetSiteId { get; set; }
        public int ParseRunId { get; set; }
        public int SessionsCount { get; set; }
        public string Sessions { get; set; }
        public string SessionsFormat { get; set; }
        public int ID { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual ParseRun ParseRun { get; set; }
        public virtual TargetSite TargetSite { get; set; }
    }
}
