//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public int Id { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> CinemaId { get; set; }
        public string Parameter { get; set; }
        public string TargetSite { get; set; }
        public string URL { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Text { get; set; }
        public int TargetSiteId { get; set; }
        public string OriginalCity { get; set; }
    
        public virtual TargetSite TargetSite1 { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual City City { get; set; }
        public virtual Cinema Cinema { get; set; }
    }
}
