//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSchedule.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetSite
    {
        public TargetSite()
        {
            this.CinemaSources = new HashSet<CinemaSource>();
            this.CitySources = new HashSet<CitySource>();
            this.Sources = new HashSet<Source>();
            this.ParseRunInfoes = new HashSet<ParseRunInfo>();
            this.MovieSources = new HashSet<MovieSource>();
            this.ShowtimeSnapshots = new HashSet<ShowtimeSnapshot>();
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int Id { get; set; }
        public string Shortcut { get; set; }
        public int Priority { get; set; }
    
        public virtual ICollection<CinemaSource> CinemaSources { get; set; }
        public virtual ICollection<CitySource> CitySources { get; set; }
        public virtual ICollection<Source> Sources { get; set; }
        public virtual ICollection<ParseRunInfo> ParseRunInfoes { get; set; }
        public virtual ICollection<MovieSource> MovieSources { get; set; }
        public virtual ICollection<ShowtimeSnapshot> ShowtimeSnapshots { get; set; }
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
